on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*"
      - "script/*"
      - "patches/*"

env:
  skia_branch: chrome/m89
  skia_commit: ed1b25f0aa5c1df9d1a4a7b6a001634bdddde7cf
  release: m89-ed1b25f0aa

jobs:

  macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: python3 script/check_release.py --release ${{ env.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: python3 script/checkout.py --skia-branch ${{ env.skia_branch }} --skia-commit ${{ env.skia_commit }}
      - run: python3 script/build.py
      - run: python3 script/archive.py
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.release }}-macos-Release-x64.zip
          path: '*.zip'
      - run: python3 script/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux:
    runs-on: ubuntu-latest
    container: ubuntu:14.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo ./script/prepare_linux.sh
      - run: python3 script/check_release.py --release ${{ env.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/checkout.py --skia-branch ${{ env.skia_branch }} --skia-commit ${{ env.skia_commit }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/build.py
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/archive.py
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.release }}-linux-Release-x64.zip
          path: '*.zip'
      - run: python3 script/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: python3 script/check_release.py --release ${{ env.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - shell: bash
        run: python3 script/checkout.py --skia-branch ${{ env.skia_branch }} --skia-commit ${{ env.skia_commit }}
      - shell: bash
        run: python3 script/build.py
      - shell: bash
        run: python3 script/archive.py
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.release }}-windows-Release-x64.zip
          path: '*.zip'
      - shell: bash
        run: python3 script/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
